### PR TITLE
added magic base system

### PR DESCRIPTION
**Pull request by Kei-7777**
added magic base system

### CODE REVIEW

**Comment by Jaimss** [comment]
wtf happened here lol. +2k -2k lines?

**Comment by bonn2** [comment]
Yeah, @Kei-7777 I would suggest you save the files you actually changed and then re-pull the repo. I can't merge this in its current state

**Comment by Jaimss** [comment]
it should look something like [this](https://github.com/MinecoreNetwork/ElementalArmor/pull/32/files) with just the changed files visible

**Comment by Kei-7777** [comment]
@bonn2 @Jaimss sorry my fault...
I try it again

**Pull request closed without merging**
